name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Semgrep  #SAST tools
        run: pip install semgrep

      - name: Run Semgrep SAST Scan
        run: semgrep --config=auto .

      - name: Run Dependency Scan #SCA
        run: |
          cd backend
          npm audit

      - name: Run Gitleaks Secret Scan  #Secret Detection
        uses: gitleaks/gitleaks-action@v2

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t governance-backend .

      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: governance-backend
          severity: HIGH,CRITICAL
          exit-code: 0


      - name: Run Checkov IaC Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true


#CD


  deploy-dev:
    needs: security-checks
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development
        run: echo "Deploying application to DEV environment"

  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Staging
        run: echo "Deploying application to STAGING environment"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        run: echo "Deploying application to PRODUCTION environment"